### ISSUE TITLE
how to solve this problem?when I run main.sh

### ISSUE THREAD

**Issue by Sunmingy** [facebookresearch/DeeperCluster#15]
![图片](https://user-images.githubusercontent.com/69899921/90624575-c17eee80-e24a-11ea-8e18-ad640c214e42.png)

**Comment by mathildecaron31** [comment]
Hi @Sunmingy,
If you're not launching main.sh to a SLURM cluster but locally then you should use `torch.distributed.launch`. For example replace https://github.com/facebookresearch/DeeperCluster/blob/d38ada109f8334f6ae4c84a218d79848a936ed6f/main.sh#L16 by `python -m torch.distributed.launch --nproc_per_node=$NGPU main.py` with `$NGPU` being the number of gpus you have.
