### ISSUE TITLE
Issues with environment variables

### ISSUE THREAD

**Issue by juliangaal** [facebookresearch/DeeperCluster#2]
I'm running into issues with environment variables after running `/.main.sh`
```bash
  File "main.py", line 251, in <module>
    main(args)
  File "main.py", line 115, in main
    training_groups, clustering_groups = init_distributed_mode(args)
  File "/media/.../deepcluster/deepcluster/core/src/utils.py", line 66, in init_distributed_mode
    args.rank = int(os.environ['RANK'])
  File "/home/.../dev/miniconda/envs/deepcluster/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```

if I understand the [default parameters](https://github.com/facebookresearch/DeeperCluster/blob/c6a54297731e1af6511b2f5d38f975e63674d6c0/main.py#L88) correctly, by default distributed training is disabled. Where are environment variables set/supposed to be set, and why is [distributed mode activated](https://github.com/facebookresearch/DeeperCluster/blob/c6a54297731e1af6511b2f5d38f975e63674d6c0/src/utils.py#L42) with these default parameters? The [docs in pytorch](https://pytorch.org/docs/stable/distributed.html#environment-variable-initialization) are a little unclear: First, they claim `RANK` will be read ("This method will read the configuration from environment variables"), but they say in the same sentence, that they will be set ("The variables to be set are")

this is my `main.sh`
```bash
python main.py \
--dump_path ./exp/deepercluster \
--data_path ./src/data/ \
--size_dataset 320 \
--workers 10 \
--sobel true \
--lr 0.1 \
--wd 0.00001 \
--nepochs 100 \
--batch_size 48 \
--reassignment 3 \
--dim_pca 4096 \
--super_classes 1 \
--rotnet true \
--k 320000 \
--warm_restart false \
--use_faiss true \
--niter 10 \
--world-size 1
```
`world_size=1` and `super_classes=1` should ensure non-distributedness, no?

Thanks for your help

**Comment by mathildecaron31** [comment]
Hi,
This implementation, as it is, supports *only* distributed mode activated. There are two scenarios:

[1-](https://github.com/facebookresearch/DeeperCluster/blob/c6a54297731e1af6511b2f5d38f975e63674d6c0/src/utils.py#L61)  Submit your job to a computer cluster. This code is adapted for SLURM job scheduler but you can modify it for your own scheduler.

[2-](https://github.com/facebookresearch/DeeperCluster/blob/c6a54297731e1af6511b2f5d38f975e63674d6c0/src/utils.py#L63)
Put `export NGPU=xx; python -m torch.distributed.launch --nproc_per_node=$NGPU` before your command (with xx the number of gpus you want). In this case, PyTorch automatically sets RANK as an environment variable.


The parameter `rank` is set automatically in [utils.py](https://github.com/facebookresearch/DeeperCluster/blob/c6a54297731e1af6511b2f5d38f975e63674d6c0/src/utils.py#L42).
The parameter `local_rank` is basically useless.
The parameter `world-size` is set manually in scenario 1 and automatically in scenario 2.
The parameter `dist-url` needs to be set manually. Refer to pytorch distributed [doc](https://pytorch.org/docs/stable/distributed.html) to set correctly the URL (specifying how to initialize the process group).

I hope this helps and I am sorry that this was not clear enough in the readme file.

**Comment by juliangaal** [comment]
with `your command` you mean `main.py`? 
```
export NGPU=2; python -m torch.distributed.launch --nproc_per_node=$NGPU main.py
```
Not sure which `train.py` file you mean from the `README`

**Comment by mathildecaron31** [comment]
If you are not submitting your bash script to a cluster, then just replace `python main.py` by `export NGPU=1; python -m torch.distributed.launch --nproc_per_node=$NGPU main.py`

**Comment by juliangaal** [comment]
Understood. Results in
```
 File "/home/..../dev/miniconda/envs/deepcluster/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 48, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for ://
```

**Comment by mathildecaron31** [comment]
By the way, your arguments are not consistent:
- you cannot use a bigger number of clusters than data points
- you cannot use `rotnet` set to `true` with a number of super_classes that is not a multiple of 4

**Comment by mathildecaron31** [comment]
Yes, you need to set `dist-url` argument (follow pytorch distributed documentation to learn how to set up the init_method).
For exemple you can use something like`file:///${HOME}/file`

**Comment by juliangaal** [comment]
Oh yeah, forgot to adjust cluster size. I'm still experimenting with a toy dataset atm.

Implementing your changes results in the same `rendezvous` error

**Comment by mathildecaron31** [comment]
You have three possible initialization methods:
https://pytorch.org/docs/stable/distributed.html#tcp-initialization
https://pytorch.org/docs/stable/distributed.html#shared-file-system-initialization
https://pytorch.org/docs/stable/distributed.html#environment-variable-initialization

If you're using only one process then the easiest is probably to use shared-file-system-initialization with `file://$PATH_TO_YOUR_SHAREDFILE`

**Comment by juliangaal** [comment]
I'm left with cuda issues, but thanks a lot for the great answers! Have a nice day
