### ISSUE TITLE
Error while cluster assignment

### ISSUE THREAD

**Issue by dizzyname** [facebookresearch/DeeperCluster#7]
I'm gonna train my own dataset (random image) less than 1 million.
When all images has been loaded and gonna get the cluster assignment, this error show up.

> Traceback (most recent call last):
  File "main.py", line 255, in <module>
    main(args)
  File "main.py", line 206, in main
    cluster_assignments = get_cluster_assignments(args, model, dataset, clustering_groups)
  File "/home/ubuntu/Documents/github/DeeperCluster/src/clustering.py", line 77, in get_cluster_assignments
    centroids,
  File "/home/ubuntu/Documents/github/DeeperCluster/src/distributed_kmeans.py", line 231, in distributed_kmeans
    assignments[it * args.batch_size: (it + 1) * args.batch_size] = I
ValueError: could not broadcast input array from shape (0) into shape (8)

This is how i ran the code [main.txt](https://github.com/facebookresearch/DeeperCluster/files/3994347/main.txt)

This is screenlog while do train [screenlog.txt](https://github.com/facebookresearch/DeeperCluster/files/3994342/screenlog.txt)

**Comment by mathildecaron31** [comment]
Hi,
Thanks for your interest in our work. The error occurs because the argument `args.size_dataset`, set at 10M, does not match the actual size of your dataset (which is around ~1M I assume). Please reopen if you still have some issues
