### ISSUE TITLE
Bug in dealing with empty clusters

### ISSUE THREAD

**Issue by semi-supervised-paper** [facebookresearch/DeeperCluster#8]
https://github.com/facebookresearch/DeeperCluster/blob/7a4699b2bfd13788a116763acc1f063cadd1a886/src/distributed_kmeans.py#L278

I think this line should be before the following two lines.
`local_counts[k] = local_counts[m] // 2;
    local_counts[m] -= local_counts[k];`

Or the reassignment can be failed.

**Comment by mathildecaron31** [comment]
Hi, thanks for raising this issue, that's indeed a bug
